# Investigación

Este documento busca darte algunas pistas sobre la carrera académica. En tu camino hacia la academia debes estar al corriente de ciertas cosas que deberías poder (y querer) **lograr**, de ciertos **problemas** que vas a enfrentar y de ciertas **habilidades** que deberías desarrollar. Todo esto te dará **autonomía** para volverte unx profesional y continuar–si te interesa–una carrera en la academia.

## ¿Quieres investigar?
Investigar no es fácil y está plagado de problemas. Hay 2 principales cosas que dificultan la formación académica: en general estos procesos están **muy poco estructurados** y a menudo hay **falta de directrices** sobre cuál es la mejor manera que ocupes tu tiempo. Te puedes evitar muchos dolores de cabeza si realizas una planificación anticipada de lo que quieres logar. Piensa primero que nada:<span style="color:blue">¿qué te motiva a comenzar un camino en la academia?</span>

Típicamente tener un **grado** y luego un **postgrado** ayuda para acceder a algunos trabajos dónde se requiere o se prefiere un título académico, especialmente para investigación. O, tal vez porque es una oportunidad para aprender mucho sobre un área específica. También puede ser porque que te brinda la oportunidad de desarrollar **ideas** y realizar una investigación original e interesante. Esto es en general verdad, pero ten en cuenta que una carrera académica es mucho trabajo y requiere una <span style="color:green">gran motivación y concentración.</span>

Es útil tener una buena idea del **área** en la que deseas especializarte y preferiblemente tener en mente un **par de preguntas de investigación** en particular en las que te gustaría trabajar. Busca libros y revistas en esa área y léelas para tener una idea de quién está haciendo qué y dónde. Aquí es donde lxs **tutorxs** entran en escena: los miembros de tu facultad deberían estar dispuestos a hablar con lxs estudiantes y ayudarles a que averigüen más sobre sus áreas de investigación y los programas de postgrado que existen. **Intenta involucrarte en una investigación**: pregunta a los profesores y asistentes si necesitan a alguien que trabaje en un proyecto en curso, o inicia tu propio proyecto de investigación independiente pidiéndole a un miembro de tu facultad que te oriente.

`r knitr::asis_output("\U0001F4A1")` <span style="color:green">**Piensa:** ¿Hay algún tema particular que te interese investigar? ¿Tienes en mente alguna pregunta de investigación?</span>

`r knitr::asis_output("\U0001F602")` <span style="color:green">**Ejemplo:** ¿Cómo afecta la experiencia emocional nuestra percepción del mundo? </span>

`r knitr::asis_output("\U0001F634")` <span style="color:green">**Ejemplo:** ¿Qué pasa en nuestro cerebro mientras dormimos? </span>

`r knitr::asis_output("\U0001F631")` <span style="color:green">**Ejemplo:** ¿Por qué nos gusta ver películas de terror y dramas? </span>

Si necesitas ideas mira <a href="https://joseluisulloafulgeri.github.io/website/research.html" target="_blank">aquí</a> y pregúntame.

**Comunícate** con miembros de tu facultad y los estudiantes que ya se han licenciado. Cuéntales sobre ti y tus intereses. **Pregúntales** en qué proyectos de investigación están trabajando. Una buena forma de hacerlo es a través de email. Un buen tutorx está dispuestx a responder este tipo de consultas (aunque si está ocupadx es posible que se demore un poco en responder). Tu mejor opción es encontrar un par de personas en la facultad con los que te **interesaría trabajar**. De esa forma, si uno no funciona o está demasiado ocupadx para aceptar a unx nuevx estudiante, tienes una alternativa. También es importante que te sientas **cómodx** en ese nicho académico. Vale la pena que hables con algunxs **estudiantes** de postgrado para averiguar qué tutorxs son buenos y qué tipo de apoyo financiero y psicológico está disponible en tu lugar de estudio.

Debido a que hay tantos estudiantes que solicitan admisión, a menudo se rechaza incluso a postulantes altamente calificados. **Debes postular a una variedad de programas**. No lo tomes como algo personal si algunos de ellos te rechazan. Para aumentar tus posibilidades de proseguir una carrera académica **sácate buenas notas**, especialmente en las clases relacionadas con tu área de interés, **desarrolla buenas relaciones con tus profesores y personas con las que trabajas** (esto es muy importante para obtener buenas recomendaciones), **trabaja en un proyecto de investigación** y ten una **idea clara de qué deseas investigar** (aunque siempre puedes cambiar de opinión más tarde). Además, es una buena idea comenzar a pensar temprano en las fuentes de financiamiento. Infórmate con tus profesores.

`r knitr::asis_output("\U0001F4A1")` <span style="color:green">**Recuerda:** Busca la ayuda de los docentes y estudiantes de tu comunidad.</span>

## ¿Qué hacer?
Durante tu desarrollo como académicx muchas veces es difícil saber exactamente qué se supone que debes estar haciendo. Tienes que investigar (o completar una tesis), pero **¿cómo empiezas? ¿a qué deberías dedicar tu tiempo?** 

Las escuelas de grado y postgrado están en general muy desestructuradas en este ámbito. Después de terminar de realizar sus cursos para muchos hay un período que le sigue que es muy difícil y estresante. Se supone que debes encontrar un **tema** de tesis (si no eres uno o una de lxs pocxs afortunadxs que ya ha encontrado un tema). Una vez que encuentres un tema lo complicado es tener un punto de referencia para saber si avanzas bien o mal.

Ser unx buenx investigadorx implica más que simplemente generar ideas brillantes e implementarlas. La mayoría de lox investigadorxs pasan la mayor parte de su tiempo **leyendo artículos, discutiendo ideas con colegas, escribiendo y revisando artículos, pensando** y, por supuesto, teniendo ideas brillantes e implementándolas. Un aspecto fundamental para ser unx investigadorx exitosx es formar parte de una **comunidad de investigadorxs**. Además, es fundamental realizar un seguimiento de tu investigación (dónde has estado y hacia dónde te diriges), debes saber cómo mantenerte **motivado** y saber cómo usar tu **tiempo** sabiamente. Es buena idea que tengas una rutina diaria.

Llevar un **diario de tus actividades e ideas de investigación** es muy útil. Puedes escribir ideas especulativas, problemas interesantes, posibles soluciones, ideas aleatorias, referencias para buscar, notas sobre artículos que hayas leído, bosquejos de artículos para escribir y citas interesantes. Léelo periódicamente. Notarás que aquellos fragmentos de pensamientos aleatorios comenzarán a juntarse y formar un patrón que a menudo se convierte en un **proyecto de investigación** o incluso en un tema de tesis.

## ¿Qué leer?
Tendrás que leer muchos documentos técnicos para familiarizarte con algún tema y mantenerte actualizado. Es posible que pases más de la mitad de tu tiempo leyendo, especialmente al principio. Esto es normal.

También es normal sentirte abrumado por la cantidad de lectura que cree que "deberías" hacer. Trata de recordar que es imposible leer todo lo que pueda ser relevante: en su lugar, **lee de forma selectiva**. Cuando empieces a leer sobre un nuevo tema, pregúntale a tu tutorx, o tus compañerxs de estudio cuáles son las revistas más útiles en su campo y pídele a tu tutorx una lista de artículos fundamentales o "clásicos" que definitivamente deberías leer. Comienza con estos artículos.

Antes de molestarte en leer cualquier documento, **asegúrate que valga la pena**.
**Escanea el título**, luego el **resumen**, luego si aún no has perdido completamente el interés, échale un vistazo a la introducción y las conclusiones. Antes de intentar obtener todos los detalles esenciales del documento, hojea todo e intenta familiarizarte con los puntos más importantes. Si todavía parece valioso y relevante, vuelve atrás y léelo todo.

A muchas personas les resulta útil tomar **notas** mientras leen. Incluso si no lo vuelves a leer más tarde eso te ayudará a enfocar tu atención y te obligará a resumir mientras lees. Y si necesitas refrescar tu memoria más tarde, volver a leer tus notas es mucho más fácil y rápido que leer todo el documento.

Algunos otros puntos a tener en cuenta al leer y evaluar artículos:

`r knitr::asis_output("\U0001F9D0")` <span style="color:blue">Asegúrate que las ideas descritas tiene un **asidero real** en los datos (en lugar de ser solo teóricamente válidas). Es decir, que lo que los autores cuentan en las conclusiones se refleja fielmente en los resultados de sus experimentos.</span>

`r knitr::asis_output("\U0001F928")` <span style="color:blue">Trata de ir más allá de palabras ostentosas: pueden sonar bien, pero no significan mucho. ¿Hay **sustancia** o alguna **idea** interesante debajo de todas esas palabras?</span>

`r knitr::asis_output("\U0001F929")` <span style="color:blue">Para comprender realmente un artículo debes comprender las **motivaciones** del problema planteado, las decisiones que se tomaron para encontrar una solución, los supuestos detrás de la solución, debes razonar si los supuestos son realistas y si pueden eliminarse sin invalidar el enfoque, reflexiona sobre las futuras direcciones de investigación, piensa en lo que realmente se logró o implementó, verifica la validez (o falta de ella) de las justificaciones teóricas o demostraciones empíricas y piensa en el potencial para extender y escalar esas ideas más allá.</span>

Mantén archivados los documentos que lees para que puedas encontrarlos de nuevo más tarde y configura una bibliografía en tu computador (o en línea). Es útil agregar campos adicionales como palabras clave y un breve resumen. Esta bibliografía será útil para referencia posterior, para escribir tu tesis y para compartir con otrxs estudiantes.

## Mantente motivadx
A veces, especialmente en los "años intermedios", puede resultar muy difícil mantener una actitud positiva y estar motivado. Muchos estudiantes de postgrado sufren de inseguridad, ansiedad e incluso aburrimiento.

En primer lugar, ten en cuenta que estos son **sentimientos normales**. Trata de encontrar un oído comprensivo: otrx estudiante de postgrado, tu tutorx o un amigx fuera de la facultad. A continuación, intenta identificar por qué tienes problemas e identifica los pasos concretos que puedes tomar para mejorar tu situación.

Para mantenerte **concentradx y motivadx** a menudo es útil tener actividades organizadas que te obliguen a administrar tu tiempo y hacer algo todos los días.

Establece reuniones periódicas con tu tutorx, asiste a seminarios o incluso actividades extracurriculares relacionadas con deporte o música, ellas pueden ayudarte a mantener un horario regular. Pone atención. Hay unos "debería" que te pueden inmovilizar y que pueden hacerte sentir tan culpable e indignx que dejas de progresar. Decirte a ti mismx que deberías tener un gran tema, que deberías terminar en X años, que deberías trabajar 4, 8 o 12 horas al día NO es útil para la mayoría de las personas. Se realista sobre lo que puedes lograr y trata de concentrarse en darte retroalimentación positiva para aquellas **tareas que si completas**, en lugar de una retroalimentación negativa para las tareas que no completas.

Establecer metas diarias, semanales y mensuales es una buena idea. Esto funciona incluso mejor si usas un **"sistema de amigos"** en el que tú y otrx estudiante se reúnen a intervalos regulares para revisar sus progresos.

`r knitr::asis_output("\U0001F601")` <span style="color:purple">Trata de encontrar personas con las que trabajar: investigar es mucho más fácil si tienes a alguien con quien intercambiar ideas y darte retroalimentación.</span>
