# Evaluación

Si miran el syllabus el módulo de "Memoria" está asociado a las siguientes evaluaciones (con su respectiva ponderación entre paréntesis):

- Informe 1 (20%)
- Informe 2 (50%)
- Presentación oral (30%)

A cada informe estará asociado un evaluación del trabajo de tesis.
Por ejemplo. La nota del Informe 1 corresponde al promedio de un informe que se entregará (50%) y una evaluación del trabajo de tesis.

El trabajo de tesis se evaluará por cada sesión/reunión.
Por cada sesión habrá una evaluación del avance de tesis, con 1 punto por evaluación.

Para tener el punto completo se deben cumplir las siguientes actividades:

- Haber enviado el acta (siguiendo las directrices de forma, contenido y tiempo indicados) [0.5 pts máx.].
- Se evaluará la compleción de las tareas de la semana [0.5 pts máx.]

Por fallos en que incurran se irán descontando puntos.

En caso de alguna excepcionalidad se puede hacer omiso de una evaluación (situación familiar, situación de salud, etc.). Para tomar en cuenta esto me deben avisar con anticipación de alguna situación particular.
